translations:
  - file: "app/assets/javascripts/i18n/translations.js"
    only:
      - "*.app_name"
      - "*.common"
      - "*.app_requests"
      - "*.activerecord.attributes"
      - "*.client"
      - "*.items.buy_button"
      - "*.browser_check"
      - "*.characters.upgrade"
      - "*.assignments"
      - "*.fights.opt_out"
      - "*.premia.refill"
      - "*.premia.buy_vip"
